all: clean compile
	@echo -e '[INFO] Done!'

clean:
	@echo -e '[INFO] Cleanup class files'
	@rm  -rf ./cs455/overlay/utils/HelperUtils.class
	@rm  -rf ./cs455/overlay/wireformats/AbstractEvent.class
	@rm  -rf ./cs455/overlay/wireformats/DefaultEvent.class
	@rm  -rf ./cs455/overlay/wireformats/RegisterRequestEvent.class
	@rm  -rf ./cs455/overlay/wireformats/SendLinkWeightsEvent.class
	@rm  -rf ./cs455/overlay/wireformats/EventFactory.class
	@rm  -rf ./cs455/overlay/wireformats/SendMessagingNodesListEvent.class
	@rm  -rf ./cs455/overlay/wireformats/DeregisterRequestEvent.class
	@rm  -rf ./cs455/overlay/wireformats/Event.class
	@rm  -rf ./cs455/overlay/wireformats/RegisterAcknowledgementEvent.class
	@rm  -rf ./cs455/overlay/wireformats/TaskInitiateEvent.class
	@rm  -rf ./cs455/overlay/wireformats/TaskCompleteEvent.class
	@rm  -rf ./cs455/overlay/wireformats/PullTrafficSummaryEvent.class
	@rm  -rf ./cs455/overlay/wireformats/TrafficSummaryEvent.class
	@rm  -rf ./cs455/overlay/wireformats/StartMessagingEvent.class
	@rm  -rf ./cs455/overlay/wireformats/TransmitMessageEvent.class
	@rm  -rf ./cs455/overlay/wireformats/SendListeningPortEvent.class
	@rm  -rf ./cs455/overlay/wireformats/ForceExitEvent.class
	@rm  -rf ./cs455/overlay/node/AbstractNode.class
	@rm  -rf ./cs455/overlay/node/MessagingNode.class
	@rm  -rf ./cs455/overlay/node/CommandListener.class
	@rm  -rf ./cs455/overlay/node/Registry.class
	@rm  -rf ./cs455/overlay/node/NodeConfiguration.class
	@rm  -rf ./cs455/overlay/node/NodeDetails.class
	@rm  -rf ./cs455/overlay/node/Node.class
	@rm  -rf ./cs455/overlay/dijkstra/ConceptualNode.class
	@rm  -rf ./cs455/overlay/dijkstra/RoutingCache.class
	@rm  -rf ./cs455/overlay/dijkstra/ShortestPathGenerator.class
	@rm  -rf ./cs455/overlay/dijkstra/NodeToNameMapping.class
	@rm  -rf ./cs455/overlay/dijkstra/ExtractLinkWeights.class
	@rm  -rf ./cs455/overlay/transport/TCPReceiverThread.class
	@rm  -rf ./cs455/overlay/transport/TCPCommunicationHandler.class
	@rm  -rf ./cs455/overlay/transport/TCPSender.class
	@rm  -rf ./cs455/overlay/transport/ConnectionObserver.class
	@rm  -rf ./cs455/overlay/transport/TCPServerThread.class
	@rm  -rf ./cs455/overlay/transport/ConnectionObservable.class
	@rm  -rf ./cs455/overlay/constants/EventConstants.class
	@rm  -rf ./cs455/overlay/constants/EventType.class
	@rm  -rf ./cs455/overlay/constants/MessageConstants.class
	@echo -e '[INFO] Done Cleanup class files'

compile:
	@echo -e '[INFO] Compiling Sources'
	@javac -d . ./src/cs455/overlay/utils/HelperUtils.java
	@javac -d . ./src/cs455/overlay/constants/EventConstants.java
	@javac -d . ./src/cs455/overlay/constants/EventType.java
	@javac -d . ./src/cs455/overlay/constants/MessageConstants.java
	@javac -d . ./src/cs455/overlay/wireformats/Event.java
	@javac -d . ./src/cs455/overlay/wireformats/AbstractEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/SendMessagingNodesListEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/DefaultEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/RegisterRequestEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/DeregisterRequestEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/SendLinkWeightsEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/TaskInitiateEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/TaskCompleteEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/PullTrafficSummaryEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/TrafficSummaryEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/RegisterAcknowledgementEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/StartMessagingEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/TransmitMessageEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/SendListeningPortEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/ForceExitEvent.java
	@javac -d . ./src/cs455/overlay/node/Node.java
	@javac -d . ./src/cs455/overlay/wireformats/EventFactory.java
	@javac -d . ./src/cs455/overlay/dijkstra/ConceptualNode.java
	@javac -d . ./src/cs455/overlay/dijkstra/RoutingCache.java
	@javac -d . ./src/cs455/overlay/dijkstra/ShortestPathGenerator.java
	@javac -d . ./src/cs455/overlay/dijkstra/NodeToNameMapping.java
	@javac -d . ./src/cs455/overlay/dijkstra/ExtractLinkWeights.java
	@javac -d . ./src/cs455/overlay/transport/TCPSender.java
	@javac -d . ./src/cs455/overlay/transport/TCPReceiverThread.java
	@javac -d . ./src/cs455/overlay/transport/TCPCommunicationHandler.java
	@javac -d . ./src/cs455/overlay/transport/ConnectionObserver.java
	@javac -d . ./src/cs455/overlay/transport/ConnectionObservable.java
	@javac -d . ./src/cs455/overlay/transport/TCPServerThread.java
	@javac -d . ./src/cs455/overlay/node/NodeDetails.java
	@javac -d . ./src/cs455/overlay/node/CommandListener.java
	@javac -d . ./src/cs455/overlay/node/AbstractNode.java
	@javac -d . ./src/cs455/overlay/node/Registry.java
	@javac -d . ./src/cs455/overlay/node/MessagingNode.java
	@javac -d . ./src/cs455/overlay/node/NodeConfiguration.java
	@echo -e '[INFO] Done Compiling Sources'

