all: clean compile
	@echo -e '[INFO] Done!'

clean:
	@echo -e '[INFO] Cleanup class files'
	@rm  -rf ./cs455/overlay/utils/HelperUtils.class
	@rm  -rf ./cs455/overlay/wireformats/AbstractEvent.class
	@rm  -rf ./cs455/overlay/wireformats/Default.class
	@rm  -rf ./cs455/overlay/wireformats/RegisterRequest.class
	@rm  -rf ./cs455/overlay/wireformats/LinkWeights.class
	@rm  -rf ./cs455/overlay/wireformats/EventFactory.class
	@rm  -rf ./cs455/overlay/wireformats/MessagingNodesList.class
	@rm  -rf ./cs455/overlay/wireformats/DeregisterRequest.class
	@rm  -rf ./cs455/overlay/wireformats/Event.class
	@rm  -rf ./cs455/overlay/wireformats/RegisterAcknowledgement.class
	@rm  -rf ./cs455/overlay/wireformats/TaskInitiate.class
	@rm  -rf ./cs455/overlay/wireformats/TaskComplete.class
	@rm  -rf ./cs455/overlay/wireformats/PullTrafficSummary.class
	@rm  -rf ./cs455/overlay/wireformats/TrafficSummary.class
	@rm  -rf ./cs455/overlay/wireformats/StartMessagingSignal.class
	@rm  -rf ./cs455/overlay/node/AbstractNode.class
	@rm  -rf ./cs455/overlay/node/MessagingNode.class
	@rm  -rf ./cs455/overlay/node/CommandListener.class
	@rm  -rf ./cs455/overlay/node/Registry.class
	@rm  -rf ./cs455/overlay/node/NodeConfiguration.class
	@rm  -rf ./cs455/overlay/node/NodeDetails.class
	@rm  -rf ./cs455/overlay/node/Node.class
	@rm  -rf ./cs455/overlay/transport/TCPReceiverThread.class
	@rm  -rf ./cs455/overlay/transport/TCPCommunicationHandler.class
	@rm  -rf ./cs455/overlay/transport/TCPSender.class
	@rm  -rf ./cs455/overlay/transport/ConnectionObserver.class
	@rm  -rf ./cs455/overlay/transport/TCPServerThread.class
	@rm  -rf ./cs455/overlay/transport/ConnectionObservable.class
	@rm  -rf ./cs455/overlay/constants/EventConstants.class
	@rm  -rf ./cs455/overlay/constants/EventType.class
	@rm  -rf ./cs455/overlay/constants/MessageConstants.class
	@echo -e '[INFO] Done Cleanup class files'

compile:
	@echo -e '[INFO] Compiling Sources'
	@javac -d . ./src/cs455/overlay/utils/HelperUtils.java
	@javac -d . ./src/cs455/overlay/constants/EventConstants.java
	@javac -d . ./src/cs455/overlay/constants/EventType.java
	@javac -d . ./src/cs455/overlay/constants/MessageConstants.java
	@javac -d . ./src/cs455/overlay/wireformats/Event.java
	@javac -d . ./src/cs455/overlay/wireformats/AbstractEvent.java
	@javac -d . ./src/cs455/overlay/wireformats/MessagingNodesList.java
	@javac -d . ./src/cs455/overlay/wireformats/Default.java
	@javac -d . ./src/cs455/overlay/wireformats/RegisterRequest.java
	@javac -d . ./src/cs455/overlay/wireformats/DeregisterRequest.java
	@javac -d . ./src/cs455/overlay/wireformats/LinkWeights.java
	@javac -d . ./src/cs455/overlay/wireformats/TaskInitiate.java
	@javac -d . ./src/cs455/overlay/wireformats/TaskComplete.java
	@javac -d . ./src/cs455/overlay/wireformats/PullTrafficSummary.java
	@javac -d . ./src/cs455/overlay/wireformats/TrafficSummary.java
	@javac -d . ./src/cs455/overlay/wireformats/RegisterAcknowledgement.java
	@javac -d . ./src/cs455/overlay/wireformats/StartMessagingSignal.java
	@javac -d . ./src/cs455/overlay/node/Node.java
	@javac -d . ./src/cs455/overlay/wireformats/EventFactory.java
	@javac -d . ./src/cs455/overlay/transport/TCPSender.java
	@javac -d . ./src/cs455/overlay/transport/TCPReceiverThread.java
	@javac -d . ./src/cs455/overlay/transport/TCPCommunicationHandler.java
	@javac -d . ./src/cs455/overlay/transport/ConnectionObserver.java
	@javac -d . ./src/cs455/overlay/transport/ConnectionObservable.java
	@javac -d . ./src/cs455/overlay/transport/TCPServerThread.java
	@javac -d . ./src/cs455/overlay/node/NodeDetails.java
	@javac -d . ./src/cs455/overlay/node/CommandListener.java
	@javac -d . ./src/cs455/overlay/node/AbstractNode.java
	@javac -d . ./src/cs455/overlay/node/Registry.java
	@javac -d . ./src/cs455/overlay/node/MessagingNode.java
	@javac -d . ./src/cs455/overlay/node/NodeConfiguration.java
	@echo -e '[INFO] Done Compiling Sources'

